content: |
    ## composer : un gestionnaire de paquets php

    ### à quoi ça sert ?

    - gérer les dépendances à votre place

    exemple :

    - [Silex/composer.json at master · silexphp/Silex](https://github.com/silexphp/Silex/blob/master/composer.json)

    - gérer l'autoloading

    ### où le trouver ?

    [getcomposer.org](https://getcomposer.org/)

    ### utilisation de composer

    ```bash
    composer.phar init
    composer.phar search yaml
    composer.phar require symfony/yaml
    ```

